name: ✨ Feature Request
description: I have a suggestion (and might want to implement myself 🙂)!
title: "[FEATURE] "
labels: ["🚦 status: awaiting triage"]
projects: ["ysun209/1"]
# projects: ["UOA-CS732-S1-2025/62"]
# type: Feature
body:
  - type: markdown
    attributes:
      value: |
        ## Acceptance Criteria

        - [ ] Clearly define what needs to be implemented.
        - [ ] Include specific requirements or conditions for the feature.
  - type: textarea
    id: user_story
    attributes:
      label: User Story
      description: "As a **type of user**, I want to **a specific feature or functionality**. So that **the benefit or value it provides**."
      value: |
        As a 
        I want to 
        So that 
      render: bash
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      render: bash
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Explain why this feature is needed and how it will benefit the project.
      render: bash
    validations:
      required: false
  - type: textarea
    attributes:
      label: Acceptance Criteria
      description: |
        Please define the acceptance criteria for the feature using the following BDD (Behavior-Driven Development) format:
        - **Given** [initial context or state],
        - **When** [action/event to trigger the behavior],
        - **Then** [expected outcome or result].

        **Examples:**
        - Given the user is on the login page, When the user clicks on the "Forgot Password?" link, Then the user should be redirected to the password recovery page.
        - Given the user is on the password recovery page, When the user enters a valid email address and clicks "Submit", Then a password reset link should be sent to the user's email address.

        Make sure to cover edge cases and all scenarios that need validation.
      value: |
        - [ ] Given , When , Then .
        - [ ] Given , When , Then .
        
  - type: textarea
    attributes:
      label: Additional context
      description: |
        Add any other context, screenshots, or references to support the feature request.
      placeholder: |
        Any extra information that might help us investigate.