name: ✨ Feature Request
description: I have a suggestion (and might want to implement myself 🙂)!
# title: ""
labels: ["🚦 status: awaiting triage"]
projects: ["ysun209/1"]
# projects: ["UOA-CS732-S1-2025/62"]
# type: Feature
body:
  - type: markdown
    attributes:
      value: |
        ## Description:

        ## Acceptance Criteria

        - [ ] Clearly define what needs to be implemented.
        - [ ] Include specific requirements or conditions for the feature.

        ## Motivation

        <!-- Explain why this feature is needed and how it will benefit the project. -->
  - type: textarea
    id: user_story
    attributes:
      label: User Story
      description: "As a <type of user>, I want to <a specific feature or functionality>. So that <the benefit or value it provides>."
      value: |
        As a 
        I want to 
        So that 
      render: bash
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      render: bash
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: |
        Add any other context, screenshots, or references to support the feature request. 