blank_issues_enabled: false
contact_links:
  - name: Ask a question or discuss a topic
    url: https://github.com/vercel/next.js/discussions
    about: Ask questions or discuss with other Next.js users in discussions.